language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
  - composer install
script:
  - phpunit --bootstrap vendor/autoload.php --coverage-clover clover.xml tests
after_success:
  - travis_retry php vendor/bin/coveralls
