language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
install:
  - composer install
  - composer require satooshi/php-coveralls
script:
  - phpunit --bootstrap vendor/autoload.php --coverage-clover clover.xml tests

matrix:
  exclude:
    - php: 5.4
      install:
        - composer install
      after_success:

after_success:
  - travis_retry php vendor/bin/coveralls
